---
title: "HR2_salaries"
output: html_document
---



```{r}

library(tidyverse)
#library(httr)
#library(jsonlite)
library(lubridate)
library(readr)   

```




```{r setup, include=FALSE}

rawdata <- "C:/Users/small/Documents/Mongomery_College/2021_fall/DATA_205/datasets"
setwd(rawdata)
knitr::opts_knit$set(root.dir = rawdata)
getwd()
  
```


```{r}

salaries <- read.csv("Employee_Salaries_-_2020.csv", header = TRUE, fileEncoding="UTF-8-BOM")


```

```{r}
str(salaries)
```



```{r}
library(funModeling) 
library(Hmisc)
library(skimr)
basic_eda <- function(data)
{
  glimpse(data)
  skim(data)
  df_status(data)
  freq(data)
  profiling_num(data)
  plot_num(data)
  describe(data)
}
basic_eda(salaries)
```

```{r}
summary(salaries$Base.Salary)
```

```{r}
library(plyr)
salaries1 <- ddply(salaries, "Gender", summarise, Base.Salary.mean=mean(Base.Salary))
salaries1
```




```{r}
salaries_hist1 <- salaries %>%
  ggplot(aes(x = Base.Salary, fill = Gender)) +
  geom_histogram(position="dodge", alpha = 0.5, color = "white")+
 # scale_fill_discrete(name = "Gender", labels = c("Female", "Male"))+
  
  geom_vline(data=salaries1, aes(xintercept=Base.Salary.mean,  colour = Gender),
               linetype="dashed", size=1)+
  
  labs(x = "Salary (in dollars)", y = "Frequency", 
       title = "MoCo Employees Salary Distribution in 2020")+
  theme_minimal()

salaries_hist1
```

```{r fig.width = 6, fig.height = 6}
salaries_box1 <- salaries %>%
  ggplot(aes(Base.Salary, Department.Name, fill = Gender)) + 
 
  ggtitle("Boxplot of MoCo Employees Salary by Gender in 2020") +
  xlab("Salary (in dollars)") +
  ylab("Departments") +
  geom_boxplot() +
  
  scale_fill_discrete(name = "Gender", labels = c("Female", "Male"))+
theme_minimal()
#coord_flip()
salaries_box1
```


```{r fig.width = 6, fig.height = 6}
ggplot(salaries, aes(x = Department.Name, y = Base.Salary, fill = Gender)) + 
  geom_bar(stat = "identity") + 
  
  labs(title = "Distribution of MoCo Employees Salary by Departments in 2020",
       x = "Deparmnents", 
       y = "Salary (in dollars)", 
       fill = "Gender") +
  coord_flip() + #flip the plot 90 degrees
  scale_y_continuous(breaks = seq(0, 45, 5)) + #scale y-axis
  theme_minimal() +
  theme(legend.position = "bottom")  #set position of the legend
  #scale_fill_brewer(palette = "Dark2") #set color palette from the RColorBrewer
```



```{r}
library(treemap)
treemap(salaries, index="Department.Name", vSize="Base.Salary", #set size
        vColor="Base.Salary", #set color
        type="value",
        title="Treemap of Salary by Departments", palette="Spectral")
        
        
```




```{r}

#library(DataExplorer)
#DataExplorer::create_report(salaries)

```





