---
title: "HR_Project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(httr)
library(jsonlite)
library(lubridate)
library(readr)  


```
## Read the csv file and set working directory


```{r}
r1 <- GET('https://data.montgomerycountymd.gov/resource/he7s-ebwb.json')

glimpse(r1)
content(r1, "text")

jsonRespText <- content(r1, as="text")
jsonRespParsed <- content(r1, as="parsed")
jsonRespParsed

salaries <- fromJSON(jsonRespText)
head(salaries)
class(salaries)
salaries1 <- as_tibble(salaries)



r2 <- GET('https://data.montgomerycountymd.gov/resource/vds6-zrjk.json')

glimpse(r2)
content(r2, "text")

jsonRespText <- content(r2, as="text")
jsonRespParsed <- content(r2, as="parsed")
jsonRespParsed

positions <- fromJSON(jsonRespText)
head(positions)
class(positions)
positions1 <- as_tibble(positions)


r3 <- GET('https://data.montgomerycountymd.gov/resource/48wg-fkab.json')

glimpse(r3)
content(r3, "text")

jsonRespText <- content(r3, as="text")
jsonRespParsed <- content(r3, as="parsed")
jsonRespParsed

classification <- fromJSON(jsonRespText)
head(classification)
class(classification)
classification1 <- as_tibble(classification)


r4 <- GET('https://data.montgomerycountymd.gov/resource/bedm-7sqa.json')

glimpse(r4)
content(r4, "text")

jsonRespText <- content(r4, as="text")
jsonRespParsed <- content(r4, as="parsed")
jsonRespParsed

personnel <- fromJSON(jsonRespText)
head(personnel)
class(personnel)
personnel1 <- as_tibble(personnel)



r5 <- GET('https://data.montgomerycountymd.gov/resource/n4gf-e8qv.json')

glimpse(r5)
content(r5, "text")

jsonRespText <- content(r5, as="text")
jsonRespParsed <- content(r5, as="parsed")
jsonRespParsed

promotion <- fromJSON(jsonRespText)
head(promotion)
class(promotion)
promotion1 <- as_tibble(promotion)


r6 <- GET('https://data.montgomerycountymd.gov/resource/2jfr-jqws.json')

glimpse(r6)
content(r6, "text")

jsonRespText <- content(r6, as="text")
jsonRespParsed <- content(r6, as="parsed")
jsonRespParsed

location <- fromJSON(jsonRespText)
head(location)
class(location)
location1 <- as_tibble(location)


```


```{r}
view(promotion2)
```


```{r}
salaries2 <- salaries1 %>%
mutate_at(c(5,6,7), as.numeric)

positions2 <- positions1 %>%
mutate_at(c('numberofopenings'), as.numeric)

classification1$average_of_base_salary <- as.numeric(gsub("[\\$,]", "",  classification1$average_of_base_salary))
classification1$number_of_employees <- as.numeric(classification1$number_of_employees)
classification2 <- classification1

personnel2 <- personnel1 %>%
mutate_at(c(2,5), as.numeric)

promotion1$female_percentage <- as.numeric(gsub("\\%", "", promotion1$female_percentage))
promotion1$male_percentage <- as.numeric(gsub("\\%", "", promotion1$male_percentage))
promotion1$grand_total <- as.numeric(gsub("\\%", "", promotion1$grand_total))
promotion2 <- promotion1

location1$percentage = as.numeric(gsub("\\%", "", location1$percentage))
location2 <- location1


```


```{r}

#rawdata <- "C:/Users/small/Documents/Mongomery_College/2021_fall/DATA_205/datasets"
#setwd(r)
#knitr::opts_knit$set(root.dir = r)
#getwd()
  
```


```{r}
#salaries <- read.csv("Employee_Salaries_-_2020.csv", header = TRUE, fileEncoding="UTF-8-BOM")
#promotions <- read.csv("Promotion_Report.csv", header = TRUE, fileEncoding="UTF-8-BOM")
#classifications <- read.csv("Average_Salary_by_Job_Classification.csv", header = TRUE, fileEncoding="UTF-8-BOM")


```


## Structure of the dataset and types of variables


```{r}
str(salaries2)
```


```{r}
str(positions2)
```


```{r}
str(classification2)
```


```{r}
str(personnel2)
```


```{r}
str(promotion2)
```


```{r}
str(location2)
```


```{r}
summary(salaries2)
```


```{r}
summary(positions2)
```


```{r}
summary(classification2)
```


```{r}
summary(personnel2)
```


```{r}
summary(promotion2)
```


```{r}
summary(location2)
```



```{r}
library(funModeling) 
library(tidyverse) 
library(Hmisc)
library(skimr)
basic_eda <- function(data)
{
  glimpse(data)
  skim(data)
  df_status(data)
  freq(data)
  profiling_num(data)
  plot_num(data)
  describe(data)
}
basic_eda(salaries2)
```


```{r}
library(DataExplorer)
DataExplorer::create_report(salaries2)
```


```{r}
basic_eda <- function(data)
{
  glimpse(data)
  skim(data)
  df_status(data)
  freq(data)
  profiling_num(data)
  plot_num(data)
  describe(data)
}
basic_eda(personnel2)
```


```{r}
basic_eda <- function(data)
{
  glimpse(data)
  skim(data)
  df_status(data)
  freq(data)
  profiling_num(data)
  plot_num(data)
  describe(data)
}
basic_eda(location2)
```


```{r}
library(DataExplorer)
DataExplorer::create_report(personnel2)
```








